name: 'WIPAC Dev Flake8'
description: 'GitHub Action Package for Running Flake8'

inputs:
  max-function-length:
    description: 'The max number of logical lines of code per function'
    required: false
    default: '200'
  max-complexity:
    description: 'The max allowed McCabe complexity value per function (1-5: simple; 6-10: readable; 11-15: harder to read; >15: potentially hard to maintain)'
    required: false
    default: '15'

runs:
  using: "composite"
  steps:
    - run: |
        pip install --upgrade pip
        pip install flake8
        pip install flake8-max-function-length
      shell: bash
    - run: |
        flake8 . \
            --ignore=E203,E226,E228,E231,E501,W503,W504 \
            --max-function-length "${{ inputs.max-function-length }}" \
            --max-complexity "${{ inputs.max-complexity }}" \
            --benchmark \
        | tee flake8_output.log
      shell: bash
    - run: |
        COMPLEX_ISSUES=$(grep -o "is too complex ([0-9]\+)" flake8_output.log || true)
        if [[ -n "$COMPLEX_ISSUES" ]]; then
          echo "::notice:: Consider refactoring these functions or increasing the 'max-complexity' input if higher complexity is justifiable."
        fi
      shell: bash
