name: 'Deprecated: WIPAC Dev Flake8'
description: 'Deprecated GitHub Action for running Flake8'

inputs:
  max-function-length:
    description: 'The max number of logical lines of code per function'
    required: false
    default: '200'
  max-complexity:
    description: 'The max allowed McCabe complexity value per function (1-5: simple; 6-10: readable; 11-15: harder to read; >15: potentially hard to maintain)'
    required: false
    default: '15'

runs:
  using: "composite"
  steps:
    - name: Deprecated
      run: |
        # step: Deprecated
        set -euo pipefail

        echo "::error::This action has been deprecated and can no longer be used (see below)."
        echo "::notice::Use the reusable workflow 'WIPACrepo/wipac-dev-workflows/.github/workflows/lint-python.yml@<ref>' instead."
        echo "::notice::See https://github.com/WIPACrepo/wipac-dev-workflows/tree/main/.github/workflows/lint-python.md for details."

        exit 1
      shell: bash
