name: Semantic Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # pypi_token: ${{ secrets.PYPI_TOKEN }}